🐛 fix inconsistent results after apply
After the change where we allow customers to configure the `space` at
the provider level, I found two issues when running Terraform apply:

Error 1:

        Error: Provider returned invalid result object after apply

        After the apply operation, the provider still indicated an unknown value for
        mondoo_integration_slack.space.space_id. All values must be known after
        apply, so this is always a bug in the provider and should be reported in the
        provider's own repository. Terraform will still save the other known object
        values in the state.

Error 2:

        Error: Provider produced inconsistent result after apply

        When applying changes to mondoo_integration_slack.space, provider
        "provider[\"registry.terraform.io/hashicorp/mondoo\"]" produced an unexpected
        new value: .space_id: was null, but now
        cty.StringVal("silly-hamilton-515695").

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.

This change fixes both of these issues.

Signed-off-by: Salim Afiune Maya <afiune@mondoo.com>